<?php
/**
 * LegLocationType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ingrid
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIW API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ingrid\Checkout\Api\Siw\Model;

/**
 * LegLocationType Class Doc Comment
 *
 * @category Class
 * @description Represents the type of location which takes part in a delivery.
 * @package  Ingrid
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LegLocationType {
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
    const WAREHOUSE = 'WAREHOUSE';
    const STORE = 'STORE';
    const HOME = 'HOME';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues() {
        return [
            self::UNKNOWN,
            self::WAREHOUSE,
            self::STORE,
            self::HOME,        ];
    }
}
